apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    {{- include "okapi.labels" . | nindent 4 }}
spec:
  clusterIP: None
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: okapi
    - port: {{ .Values.service.second_port.port }}
      name: hazelcast
  selector:
    {{- include "okapi.selectorLabels" . | nindent 4 }}
