{{- if .Values.ingress.tls }}
{{- range .Values.ingress.tls }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName }}
type: kubernetes.io/tls
data:
  server.crt: |
    {{ .cert | indent 4 | trimPrefix "    " }}

  server.key: |
    {{ .key | indent 4 | trimPrefix "    " }}
{{- end }}
{{- end }}